### ISSUE TITLE
NullPointerException in MethodHookImpl.java

### ISSUE THREAD

**Issue by melonaerial** [idanr1986/droidmon#2]
Hello!
https://github.com/idanr1986/droidmon/blob/master/src/com/cuckoodroid/droidmon/MethodHookImpl.java this file in line 43 always throws NullPointerException and Hooks doesn't work. So i have patched you application using apktool(i'm new in Android and i have problems to make you application build in IDEA Studio) and i have deleted that if and it works great! So please fix the problem, cause CuckooDroid framework doesn't work without this app. cause most interesting part of CuckooDroid it is API Calls for me.

**Comment by idanr1986** [comment]
ill check it thanks

**Comment by berii** [comment]
There is a missing attribute in the hooks.json called trace (as you said line 43 in MethodHookImpl.java). So the hooks.json should look like:
{
    "hookConfigs": [
        {
            "class_name": "android.telephony.TelephonyManager", 
            "method": "getDeviceId", 
            "thisObject": false, 
            "type": "fingerprint"
        }, 
        {
            "class_name": "android.telephony.TelephonyManager", 
            "method": "getSubscriberId", 
            "thisObject": false, 
            "type": "fingerprint"
        }
    ],
"trace":false
}

**Comment by melonaerial** [comment]
Yep! This problem is because of this line of code: https://github.com/idanr1986/droidmon/blob/master/src/com/cuckoodroid/droidmon/InstrumentationManager.java#L83 .
I think developers should add check for TRACE == null, and if so set it to false as in default static constructor. Or add "trace" parameter to documentation, as u said.

**Comment by idanr1986** [comment]
fixed the example in the README and added hooks.json example file
