### ISSUE TITLE
How does the Class MethodApiType be used?

### ISSUE THREAD

**Issue by chychenhongyi** [idanr1986/droidmon#4]
After reading the source code, I cannot find a example for assigning the value of "type" in the hook file "hooks.jason". Either can I find how the "type" value be used in the source code.
All I can find is it used as a formal parameter in Logger class.

So What purpose does the Class MethodApiType designed to  achieve?

**Comment by idanr1986** [comment]
this for future view of all the called api calls like in cuckoo

**Comment by chychenhongyi** [comment]
Oh~~~, that's interesting. Thanks for your patiently answering.

**Comment by idanr1986** [comment]
this is for support in the behavioural analysis view of cuckoo
like in https://malwr.com/analysis/NDJkYTczZDRkZDFlNGMxN2FkOThmNDkxZDUxNjYyYWM/
